# Generated by Django 3.1 on 2020-08-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200817_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(default='blog/post_title_images/default.jpg', upload_to='blog/post_title_images'),
        ),
    ]
